version: 0.2
phases:
   install:
     runtime-versions:
       python: 3.7
     commands:
       - pip install cfn-lint
   pre_build:
     commands:
       - echo CFN-LINT started on `date`
   build:
     commands:
       - cfn-lint -t templates/*.yaml
   post_build:
     commands:
       - echo CFN-LINT completed on `date`