
version: 0.2
phases:
  build:
    commands:
      - git clone https://github.com/awslabs/git-secrets.git
      - cd git-secrets/
      - make install
      - cd ..
      - git init
      - git secrets --install
      - git secrets --register-aws
      - git secrets --add --allowed --literal 's.c.e.1.3'
      - git secrets --add 's.c.e.1.3'
      - git secrets --scan -r .
  post_build:
    commands:
      - echo "Git Secrets Execution Finished..."