version: 0.2
env:
  parameter-store:
    TokenAqua: "/DevTools/TokenAqua"
phases:
  install:
    runtime-versions:
      docker: 18

  build:
    commands:
      - echo Building the Docker image to Aqua analysis..
      - echo "\r\n" >> Dockerfile
      - echo "ADD https://get.aquasec.com/microscanner ." >> Dockerfile
      - echo "RUN chmod +x microscanner" >> Dockerfile
      - echo "RUN ./microscanner $TokenAqua --html --continue-on-failure " >> Dockerfile
      - cat Dockerfile
      - docker build --no-cache . >> results.html
      - sed -n '/<html/,/<\/html/p' results.html >> report-aqua.html
      - cat report-aqua.html
      - status=$(grep -wc "continue-on-failure" report-aqua.html); if [ $status -eq 0 ]; then exit 0; else exit 1; fi
  post_build:
    commands:
      - echo "Aqua Microscanner Execution Finished..."